/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    colors: {
      background: '#FFFFFF',
      foreground: '#090A0F',
      card: '#FFFFFF',
      'card-foreground': '#090A0F',
      popover: '#FFFFFF',
      'popover-foreground': '#090A0F',
      primary: '#1DBF73',
      'primary-foreground': '#FFF5F5',
      secondary: '#F4F4F8',
      'secondary-foreground': '#1A1A33',
      muted: '#F4F4F8',
      'muted-foreground': '#383850',
      accent: '#F4F4F8',
      'accent-foreground': '#1A1A33',
      destructive: '#F52B2B',
      'destructive-foreground': '#FAFAFA',
      border: '#E0E0EB',
      input: '#E0E0EB',
      warning: '#FF6707',
    },
    fontFamily: {
      sans: ['Roboto', 'sans-serif'],
    },
    fontSize: {
      xs: '0.75rem',
      s: '0.875rem',
      m: '1rem',
      l: '1.25rem',
      xl: '1.5rem',
      '2xl': '2rem',
    },
    extend: {},
  },
  plugins: [],
}
